### ISSUE TITLE
OpenTofu doesn't work in new Ephemeral Executors in 2.22.0-beta.5

### ISSUE THREAD

**Issue by adamlc** [AzBuilder/terrakube#1085]
### Bug description 🐞

When running a OpenTofu workspace in a ephemeral executor it fails with the following error:

```
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "this.tofuReleases" is null
	at org.terrakube.terraform.TerraformDownloader.downloadTofuVersion(TerraformDownloader.java:255)
	at org.terrakube.terraform.TerraformClient.getTerraformLauncher(TerraformClient.java:283)
	at org.terrakube.terraform.TerraformClient.run(TerraformClient.java:208)
	at org.terrakube.terraform.TerraformClient.init(TerraformClient.java:104)
	at org.terrakube.executor.service.terraform.TerraformExecutorServiceImpl.executeTerraformInit(TerraformExecutorServiceImpl.java:398)
	at org.terrakube.executor.service.terraform.TerraformExecutorServiceImpl.plan(TerraformExecutorServiceImpl.java:103)
	at org.terrakube.executor.service.executor.ExecutorJobImpl.createJob(ExecutorJobImpl.java:53)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Steps to reproduce

1. Create new OpenTofu workspace
2. Set environment variable `TERRAKUBE_ENABLE_EPHEMERAL_EXECUTOR=1`
3. Run a plan
4. Plan hangs and the above error is shown in the job executor logs

### Expected behavior

Job should run successfully in an external executor, just like Terraform.

### Anything else?

I assume this is due to #1029. When testing this release I had to add the env var `CustomTofuReleasesUrl=https://api.github.com/repos/opentofu/opentofu/releases` to the API and Executor.

I assume this environment variable isn't passed to job when created in kubernetes.

**Comment by alfespa17** [comment]
I think I will have to add a default value so it does not break

**Comment by adamlc** [comment]
Can confirm all fixed, thanks!
