### ISSUE TITLE
Bitbucket Refresh Token Fails

### ISSUE THREAD

**Issue by alfespa17** [AzBuilder/terrakube#111]
Sometimes refreshing bitbucket token fails with the following error

```
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.azbuilder.api.plugin.vcs.TokenService$$EnhancerBySpringCGLIB$$ae52833.refreshAccessToken(<generated>) ~[classes/:1.7.3]
	at org.azbuilder.api.plugin.scheduler.ScheduleVcs.execute(ScheduleVcs.java:39) ~[classes/:1.7.3]
	at org.azbuilder.api.plugin.scheduler.ScheduleVcs$$FastClassBySpringCGLIB$$5fb5ebcb.invoke(<generated>) ~[classes/:1.7.3]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.14.jar:5.3.14]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.14.jar:5.3.14]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698) ~[spring-aop-5.3.14.jar:5.3.14]
	at org.azbuilder.api.plugin.scheduler.ScheduleVcs$$EnhancerBySpringCGLIB$$130a8af5.execute(<generated>) ~[classes/:1.7.3]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar:na]
	... 1 common frames omitted
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.4.10.jar:3.4.10]
		... 22 common frames omitted
Caused by: java.util.concurrent.TimeoutException: Did not observe any item or terminal signal within 10000ms in 'flatMap' (and no fallback has been configured)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295) ~[reactor-core-3.4.10.jar:3.4.10]
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280) ~[reactor-core-3.4.10.jar:3.4.10]
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419) ~[reactor-core-3.4.10.jar:3.4.10]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.10.jar:3.4.10]
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271) ~[reactor-core-3.4.10.jar:3.4.10]
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286) ~[reactor-core-3.4.10.jar:3.4.10]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.4.10.jar:3.4.10]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.4.10.jar:3.4.10]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
2022-01-14T14:00:10.479545126Z
```

**Comment by jsidney** [comment]
@alfespa17  - i noticed that once i have configured my bitbucket cloud vcs provider, it all works for a period of time (uploading modules etc), but after a few hours, it starts to fail (and cannot pull the the modules and versions etc). would this issue be related to this bug?

**Comment by alfespa17** [comment]
Hello @jsidney are you facing the same issue?

The token that terrakube generates to use the bitbucket repos has a two hours expiration time, if remember correctly terrakube tries to refresh the token every our, with some internal job, so it will try two times before the token expires. Are yo facing the same issue? Could you share the error logs?

**Comment by alfespa17** [comment]
Let me create I bitbucket connection and test what could be causing the issue

**Comment by alfespa17** [comment]
I have created a new beta version, I think this could fix the issue to refresh the token, maybe you can give it a try @jsidney 
 overriding the api version when deploying the helm chart like this:

```bash
api:
  version: 2.16.0-beta.4
```

**Comment by jsidney** [comment]
Thanks @alfespa17 ! Will run an upgrade and keep you posted:)

**Comment by alfespa17** [comment]
After doing some more testing I was able to find the root cause for this issue.

By the way thank for reporting this, it looks like it could impact other VCS connections in certain situations. I will release the final fix today after some more testing on my side

**Comment by alfespa17** [comment]
The latest release 2.16.0 include the fix for the VCS issue, if you update your helm repository to [3.9.0](https://github.com/AzBuilder/terrakube-helm-chart/releases/tag/terrakube-3.9.0) you will be using the Terrakube 2.16.0 version by default. I think I can finally close this issue I haven been testing for a few hours and it is working as expected.

**Comment by jsidney** [comment]
Thanks for the update man! 
i havent updated the helm chart (still using your beta release... but will be updating ASAP). it does look like its working!
