### ISSUE TITLE
Terraform plan never runs

### ISSUE THREAD

**Issue by erick-prosimo** [AzBuilder/terrakube#305]
### Bug description 🐞

Public or private repos show the same behavior when adding to a workspace. When running the built-in "Terraform Plan" it hangs at "Running Terraform Plan pending": Waiting logs...

![image](https://user-images.githubusercontent.com/100948345/216489622-45772ab0-ea0d-49c0-be93-2c5e829ede46.png)

There is no other data anywhere indicating what is actually happening. Additionally once something enters this state there is no way to stop/cancel the run. The only way to remove this "queue" is to completely delete the workspace with all the variables defined, etc. and try again. Unfortunately it never works.

### Steps to reproduce

Create a workspace and try to run any operation.

**Comment by alfespa17** [comment]
Hello @erick-prosimo can you create one job and check the logs of the pods for the API and Executor component.

You can get the logs using the following:

```bash 
kubectl get pods -n terrakube
kubectl logs <POD_NAME_API> -n terrakube
kubectl logs <POD_NAME_EXECUTOR> -n terrakube
```

When a job is create is should take up to 60 seconds to start. 

By the way you can also use [lens](https://k8slens.dev/) to see the logs in real time it is easier than using kubectl.

![image](https://user-images.githubusercontent.com/4461895/216626288-45300036-f23f-4758-8f2a-71003ef28516.png)

**Comment by alfespa17** [comment]
Could you check the API logs, you should be able to see something like this when the jobs is triggerred.

```bash
2023-02-03 15:36:00.206  INFO 1 --- [ryBean_Worker-1] o.t.api.plugin.scheduler.ScheduleJob     : Checking Job 1 Status pending
2023-02-03 15:36:00.210  INFO 1 --- [ryBean_Worker-1] o.t.a.p.scheduler.job.tcl.TclService     : InitialJobSetup 1
2023-02-03 15:36:00.264  INFO 1 --- [ryBean_Worker-1] o.t.a.p.scheduler.job.tcl.TclService     : FlowConfig: 
 FlowConfig(flow=[Flow(type=terraformPlan, team=null, name=Running Terraform Plan, step=100, commands=null)])
2023-02-03 15:36:00.273  INFO 1 --- [ryBean_Worker-1] o.t.a.p.scheduler.job.tcl.TclService     : Custom Job Setup: 
 FlowConfig(flow=[Flow(type=terraformPlan, team=null, name=Running Terraform Plan, step=100, commands=null)])
2023-02-03 15:36:00.274  INFO 1 --- [ryBean_Worker-1] o.t.a.p.scheduler.job.tcl.TclService     : Creating step: Flow(type=terraformPlan, team=null, name=Running Terraform Plan, step=100, commands=null)
2023-02-03 15:36:00.274  INFO 1 --- [ryBean_Worker-1] o.t.a.p.scheduler.job.tcl.TclService     : Step name Running Terraform Plan

2023-02-03 15:36:00.277  INFO 1 --- [ryBean_Worker-1] o.t.a.p.scheduler.job.tcl.TclService     : Parent 1 Step created 678e8362-a731-4073-bdec-f020160dc3ee
2023-02-03 15:36:00.308  INFO 1 --- [ryBean_Worker-1] o.t.a.p.scheduler.job.tcl.TclService     : Pending steps 1
2023-02-03 15:36:00.308  INFO 1 --- [ryBean_Worker-1] o.t.a.p.scheduler.job.tcl.TclService     : Next Command: 100
2023-02-03 15:36:00.309  INFO 1 --- [ryBean_Worker-1] o.t.a.p.scheduler.job.tcl.TclService     : FlowConfig: 
 FlowConfig(flow=[Flow(type=terraformPlan, team=null, name=Running Terraform Plan, step=100, commands=null)])
2023-02-03 15:36:00.310  INFO 1 --- [ryBean_Worker-1] o.t.api.plugin.scheduler.ScheduleJob     : Execute command: terraformPlan 
 null
2023-02-03 15:36:00.319  INFO 1 --- [ryBean_Worker-1] o.t.a.p.scheduler.job.tcl.TclService     : Pending steps 1
2023-02-03 15:36:00.323  INFO 1 --- [ryBean_Worker-1] o.t.a.p.s.j.t.executor.ExecutorService   : Pending Job: 1 WorkspaceId: a4ad32fe-fff5-45e0-89b7-136d70f5e68c
2023-02-03 15:36:00.325  INFO 1 --- [ryBean_Worker-1] o.t.a.p.s.j.t.executor.ExecutorService   : Checking Variables
2023-02-03 15:36:00.325  INFO 1 --- [ryBean_Worker-1] o.t.a.p.s.j.t.executor.ExecutorService   : Private Repository GITHUB
2023-02-03 15:36:00.445  INFO 1 --- [ryBean_Worker-1] o.t.a.p.s.j.t.executor.ExecutorService   : Sending Job: /n ExecutorContext(commandList=null, type=terraformPlan, organizationId=24351f42-7963-49a9-af4d-2a0e4aa3a92b, workspaceId=a4ad32fe-fff5-45e0-89b7-136d70f5e68c, jobId=1, stepId=678e8362-a731-4073-bdec-f020160dc3ee, terraformVersion=1.2.9, source=https://github.com/alfespa17/terrakube-workspace.git, branch=main, folder=/workspace1, vcsType=GITHUB, accessToken=****, environmentVariables={TF_IN_AUTOMATION=1}, variables={})
2023-02-03 15:36:00.491  INFO 1 --- [ryBean_Worker-1] o.t.a.p.s.j.t.executor.ExecutorService   : Response Status: 202
2023-02-03 15:36:00.492  INFO 1 --- [ryBean_Worker-1] o.t.api.plugin.scheduler.ScheduleJob     : Executing Job 1 Step Id 678e8362-a731-4073-bdec-f020160dc3ee
```


 You should be able to see the job information that is sent to execution inside the API logs.

```
2023-02-03 15:36:00.445  INFO 1 --- [ryBean_Worker-1] o.t.a.p.s.j.t.executor.ExecutorService   : Sending Job: /n ExecutorContext(commandList=null, type=terraformPlan, organizationId=24351f42-7963-49a9-af4d-2a0e4aa3a92b, workspaceId=a4ad32fe-fff5-45e0-89b7-136d70f5e68c, jobId=1, stepId=678e8362-a731-4073-bdec-f020160dc3ee, terraformVersion=1.2.9, source=https://github.com/alfespa17/terrakube-workspace.git, branch=main, folder=/workspace1, vcsType=GITHUB, accessToken=****, environmentVariables={TF_IN_AUTOMATION=1}, variables={})
```

**Comment by erick-prosimo** [comment]
Yeah, I see it send the job, but the executor is throwing that error.


`2023-02-03 16:17:00.687  INFO 1 --- [ryBean_Worker-8] o.t.api.plugin.scheduler.ScheduleJob     : Execute command: terraformPlan 
 null
2023-02-03 16:17:00.688  INFO 1 --- [ryBean_Worker-8] o.t.a.p.scheduler.job.tcl.TclService     : Pending steps 1
2023-02-03 16:17:00.689  INFO 1 --- [ryBean_Worker-8] o.t.a.p.s.j.t.executor.ExecutorService   : Pending Job: 9 WorkspaceId: 3c0286b1-5aec-4f57-a828-ea2a86e3be2b
2023-02-03 16:17:00.689  INFO 1 --- [ryBean_Worker-8] o.t.a.p.s.j.t.executor.ExecutorService   : Checking Variables
2023-02-03 16:17:00.689  INFO 1 --- [ryBean_Worker-8] o.t.a.p.s.j.t.executor.ExecutorService   : Private Repository GITHUB
2023-02-03 16:17:00.713  INFO 1 --- [ryBean_Worker-8] o.t.a.p.s.j.t.executor.ExecutorService   : Sending Job: /n ExecutorContext(commandList=null, type=terraformPlan, organizationId=2aa128f5-5bab-40d7-aba5-2dead24549e4, workspaceId=3c0286b1-5aec-4f57-a828-ea2a86e3be2b, jobId=9, stepId=66763c3e-2b9b-4cc2-8b0c-d87bc412fdb8, terraformVersion=1.3.4, source=https://github.com/<hidden>/terraform-aws-wordpress.git, branch=main, folder=/, vcsType=GITHUB, accessToken=****, environmentVariables={TF_IN_AUTOMATION=1}, variables={})
2023-02-03 16:17:00.713  INFO 1 --- [ryBean_Worker-8] o.t.a.p.s.j.t.executor.ExecutorService   : Response Status: 202
2023-02-03 16:17:00.714  INFO 1 --- [ryBean_Worker-8] o.t.api.plugin.scheduler.ScheduleJob     : Executing Job 9 Step Id 66763c3e-2b9b-4cc2-8b0c-d87bc412fdb8
2023-02-03 16:17:03.580  INFO 1 --- [nio-8080-exec-9] p.s.a.d.DexAuthenticationManagerResolver : Using Dex JWT Authentication Provider`

**Comment by erick-prosimo** [comment]
`
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.executor.ExecutorJobImpl - Create Job for Organization 2aa128f5-5bab-40d7-aba5-2dead24549e4 Workspace 3c0286b1-5aec-4f57-a828-ea2a86e3be2b 
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - User Home Directory: /home/cnb
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Workspace git clone directory: /home/cnb/.terraform-spring-boot/executor/2aa128f5-5bab-40d7-aba5-2dead24549e4/3c0286b1-5aec-4f57-a828-ea2a86e3be2b/.originRepository
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Workspace working directory: /home/cnb/.terraform-spring-boot/executor/2aa128f5-5bab-40d7-aba5-2dead24549e4/3c0286b1-5aec-4f57-a828-ea2a86e3be2b
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - vcsType: GITHUB
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Commit Id: 58d80304012e66d0736485402e38e3d6e69334cc
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Writing commit id to /home/cnb/.terraform-spring-boot/executor/2aa128f5-5bab-40d7-aba5-2dead24549e4/3c0286b1-5aec-4f57-a828-ea2a86e3be2b/commitHash.info
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Copy files from folder /home/cnb/.terraform-spring-boot/executor/2aa128f5-5bab-40d7-aba5-2dead24549e4/3c0286b1-5aec-4f57-a828-ea2a86e3be2b/.originRepository/ to /home/cnb/.terraform-spring-boot/executor/2aa128f5-5bab-40d7-aba5-2dead24549e4/3c0286b1-5aec-4f57-a828-ea2a86e3be2b
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Copy outputs.tf to /home/cnb/.terraform-spring-boot/executor/2aa128f5-5bab-40d7-aba5-2dead24549e4/3c0286b1-5aec-4f57-a828-ea2a86e3be2b
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Copy providers.tf to /home/cnb/.terraform-spring-boot/executor/2aa128f5-5bab-40d7-aba5-2dead24549e4/3c0286b1-5aec-4f57-a828-ea2a86e3be2b
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Copy README.md to /home/cnb/.terraform-spring-boot/executor/2aa128f5-5bab-40d7-aba5-2dead24549e4/3c0286b1-5aec-4f57-a828-ea2a86e3be2b
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Copy main.tf to /home/cnb/.terraform-spring-boot/executor/2aa128f5-5bab-40d7-aba5-2dead24549e4/3c0286b1-5aec-4f57-a828-ea2a86e3be2b
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Copy variables.tf to /home/cnb/.terraform-spring-boot/executor/2aa128f5-5bab-40d7-aba5-2dead24549e4/3c0286b1-5aec-4f57-a828-ea2a86e3be2b
[threadPoolTaskExecutor-1] INFO org.terrakube.executor.service.workspace.SetupWorkspaceImpl - Copy .git to /home/cnb/.terraform-spring-boot/executor/2aa128f5-5bab-40d7-aba5-2dead24549e4/3c0286b1-5aec-4f57-a828-ea2a86e3be2b
[threadPoolTaskExecutor-1] ERROR org.terrakube.executor.service.workspace.security.WorkspaceSecurityImpl - Generate Dex Authentication Private Token
[threadPoolTaskExecutor-1] ERROR org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler - Unexpected exception occurred invoking async method: public void org.terrakube.executor.service.executor.ExecutorJobImpl.createJob(org.terrakube.executor.service.mode.TerraformJob)
io.jsonwebtoken.io.DecodingException: Illegal base64url character: '+'
	at io.jsonwebtoken.io.Base64.ctoi(Base64.java:221)
	at io.jsonwebtoken.io.Base64.decodeFast(Base64.java:270)
	at io.jsonwebtoken.io.Base64Decoder.decode(Base64Decoder.java:36)
	at io.jsonwebtoken.io.Base64Decoder.decode(Base64Decoder.java:23)
	at io.jsonwebtoken.io.ExceptionPropagatingDecoder.decode(ExceptionPropagatingDecoder.java:36)
	at org.terrakube.executor.service.workspace.security.WorkspaceSecurityImpl.generateAccessToken(WorkspaceSecurityImpl.java:50)
	at org.terrakube.executor.service.workspace.security.WorkspaceSecurityImpl.addTerraformCredentials(WorkspaceSecurityImpl.java:87)
	at org.terrakube.executor.service.workspace.SetupWorkspaceImpl.prepareWorkspace(SetupWorkspaceImpl.java:60)
	at org.terrakube.executor.service.executor.ExecutorJobImpl.createJob(ExecutorJobImpl.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by alfespa17** [comment]
It looks like the issue is related to the Terrakube Internal secret, this is used to sign the token for internal component communication.

https://github.com/AzBuilder/terrakube/blob/main/executor/src/main/java/org/terrakube/executor/service/workspace/security/WorkspaceSecurityImpl.java#L50

Quick question when you deployed the helm chart did you used a 32 random character? like this example:

```yaml
security:
  adminGroup: "<<CHANGE_THIS>>" # This should be your Azure AD group name
  patSecret: "<<CHANGE_THIS>>"  # Sample Key 32 characters z6QHX!y@Nep2QDT!53vgH43^PjRXyC3X 
  internalSecret: "<<CHANGE_THIS>>" # Sample Key 32 characters Kb^8cMerPNZV6hS!9!kcD*KuUPUBa^B3 
  dexClientId: "microsoft"
  dexClientScope: "email openid profile offline_access groups"
  dexIssuerUri: "https://terrakube-api.domain.com/dex" #
```

Can you try updating the value of the internal secret?

**Comment by alfespa17** [comment]
The secret should be 32 character long

**Comment by erick-prosimo** [comment]
OK, will give it a try here in a sec. One more question, is there a way to set global variables that are persisted so they dont need to be added everytime?

**Comment by erick-prosimo** [comment]
Yup, confirmed, secret was the issue. I think that part was also unclear in the docs. Probably need to call out it must be a base64 compatible string that is 32 characters in length.

**Comment by alfespa17** [comment]
You can do that using "global variables" in the organization, we added that feature some time ago https://github.com/AzBuilder/terrakube/pull/181 but it is only available using the API.

You can check the docs [here](https://docs.terrakube.org/api/methods/globalvar)

There is an open issue to add that in the UI https://github.com/AzBuilder/terrakube/issues/207

**Comment by erick-prosimo** [comment]
OK, cool. I did see it in the CLI/API, but wanted to make sure it was usable. I'll give that a shot next. Thanks so much! 

¡Disfruta tu fin de semana!

**Comment by alfespa17** [comment]
Muchas gracias, feliz fin de semana!!!

**Comment by alfespa17** [comment]
Comments about the secret requirements was added in the helm chart docs.

https://github.com/AzBuilder/terrakube-helm-chart/pull/42
