### ISSUE TITLE
Timeout exception when storing more than 53 modules

### ISSUE THREAD

**Issue by ruankr** [AzBuilder/terrakube#479]
### Bug description 🐞

When adding more than around 53 Modules to the Registry the whole registry seems to break down due to a timeout. Once this happens the Registry page does not display any modules and even api calls start to fail (if trying to get the list of modules). 

![image](https://github.com/AzBuilder/terrakube/assets/63055439/6da928dd-b28c-460e-801f-adeb8e6529cf)

Looking at the api logs this shows a timeout is occurring:
```text
2023-08-22 06:15:29.041  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:29.687  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:30.204  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:30.732  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:31.337  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:31.897  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:32.461  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:33.117  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:33.696  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:34.258  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:34.793  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:35.322  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:35.830  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:36.417  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:36.952  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:37.600  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:38.149  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:38.696  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:39.280  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:39.808  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:40.358  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:40.893  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:41.481  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:42.049  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:42.620  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:43.206  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:43.736  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:44.313  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:44.900  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:45.460  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:46.056  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:46.626  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:47.178  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:47.704  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:48.290  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:48.802  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:49.367  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:49.961  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:50.505  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:51.085  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:51.668  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:52.225  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:52.761  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:53.408  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:53.955  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:54.480  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:55.009  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:55.535  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:56.071  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:56.676  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:57.195  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:57.743  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:58.245  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:58.826  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:59.022  WARN 1 --- [nio-8080-exec-5] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.context.request.async.AsyncRequestTimeoutException]
2023-08-22 06:15:59.407  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:15:59.981  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:16:00.587  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:16:01.150  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
2023-08-22 06:16:01.708  INFO 1 --- [       task-356] org.terrakube.api.rs.module.Module       : vcs using GITHUB
```

When browsing back to the Organization after this happens further errors are observed:
```text
2023-08-22 06:19:52.493  WARN 1 --- [nio-8080-exec-8] o.apache.catalina.core.AsyncContextImpl  : onError() call failed for listener of type [org.apache.catalina.core.AsyncListenerWrapper]

java.lang.IllegalArgumentException: Cannot dispatch without an AsyncContext
        at org.springframework.util.Assert.notNull(Assert.java:201) ~[spring-core-5.3.28.jar:5.3.28]
        at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:131) ~[spring-web-5.3.28.jar:5.3.28]
        at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401) ~[spring-web-5.3.28.jar:5.3.28]
        at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$2(WebAsyncManager.java:323) ~[spring-web-5.3.28.jar:5.3.28]
        at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.lambda$onError$0(StandardServletAsyncWebRequest.java:146) ~[spring-web-5.3.28.jar:5.3.28]
        at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
        at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onError(StandardServletAsyncWebRequest.java:146) ~[spring-web-5.3.28.jar:5.3.28]
        at org.apache.catalina.core.AsyncListenerWrapper.fireOnError(AsyncListenerWrapper.java:49) ~[tomcat-embed-core-9.0.76.jar:9.0.76]
        at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:394) ~[tomcat-embed-core-9.0.76.jar:9.0.76]
        at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:240) ~[tomcat-embed-core-9.0.76.jar:9.0.76]
        at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241) ~[tomcat-embed-core-9.0.76.jar:9.0.76]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:57) ~[tomcat-embed-core-9.0.76.jar:9.0.76]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) ~[tomcat-embed-core-9.0.76.jar:9.0.76]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) ~[tomcat-embed-core-9.0.76.jar:9.0.76]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-9.0.76.jar:9.0.76]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.76.jar:9.0.76]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.76.jar:9.0.76]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.76.jar:9.0.76]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

### Steps to reproduce

Add Github as a VCS provider as per [instructions](https://docs.terrakube.io/user-guide/vcs-providers/github.com)
Add 52+ modules to the registry, then try to reload the Registry page from the UI

### Expected behavior

Registry page lazy loads and displays modules

### Anything else?

Running in Azure Kubernetes and deployed using HELM

**Comment by alfespa17** [comment]
When you open that page Terrakube is checking for each module the current "tags/releases/version" and it creates an array with all the "versions", maybe is not doing that in the most efficient way.

https://github.com/AzBuilder/terrakube/blob/main/api/src/main/java/org/terrakube/api/rs/module/Module.java#L90

```java
    @Transient
    @ComputedAttribute
    public List<String> getVersions(RequestScope requestScope) {
        List<String> versionList = new ArrayList<>();
        try {
            CredentialsProvider credentialsProvider = null;
            TransportConfigCallback transportConfigCallback = null;
            Map<String, Ref> tags = null;
            if (vcs != null) {
                log.info("vcs using {}", vcs.getVcsType());
                switch (vcs.getVcsType()) {
                    case GITHUB:
                        credentialsProvider = new UsernamePasswordCredentialsProvider(vcs.getAccessToken(), "");
                        break;
                    case BITBUCKET:
                        credentialsProvider = new UsernamePasswordCredentialsProvider("x-token-auth", vcs.getAccessToken());
                        break;
                    case GITLAB:
                        credentialsProvider = new UsernamePasswordCredentialsProvider("oauth2", vcs.getAccessToken());
                        break;
                    case AZURE_DEVOPS:
                        credentialsProvider = new UsernamePasswordCredentialsProvider("dummy", vcs.getAccessToken());
                        break;
                    default:
                        credentialsProvider = null;
                        break;
                }

                tags = Git.lsRemoteRepository()
                        .setTags(true)
                        .setRemote(source)
                        .setCredentialsProvider(credentialsProvider)
                        .callAsMap();
            }

            if (ssh != null){
                log.info("vcs using ssh {}", ssh.getId());

                transportConfigCallback = transport -> {
                    if(transport instanceof SshTransport) {
                        if( transport instanceof SshTransport) {
                            TerrakubeSshdSessionFactory terrakubeSshdSessionFactory = TerrakubeSshdSessionFactory
                                    .builder()
                                    .sshId(ssh.getId().toString())
                                    .sshFileName(ssh.getSshType().getFileName())
                                    .privateKey(ssh.getPrivateKey())
                                    .build();
                            ((SshTransport) transport).setSshSessionFactory(terrakubeSshdSessionFactory.getSshdSessionFactory());
                        }
                    }
                };

                tags = Git.lsRemoteRepository()
                        .setTags(true)
                        .setRemote(source)
                        .setTransportConfigCallback(transportConfigCallback)
                        .callAsMap();
            }

            if (ssh == null && vcs == null){
                tags = Git.lsRemoteRepository()
                        .setTags(true)
                        .setRemote(source)
                        .callAsMap();
            }

            tags.forEach((key, value) -> {
                versionList.add(key.replace("refs/tags/", ""));
            });
        } catch (GitAPIException e) {
            log.error(e.getMessage());
        }
        return versionList;
    }
````

I will try to reproduce that error and check a way to fix it, but for now I think that as a work around you could split your modules in two or three organizations, there ir no limit to create organization inside Terrakube.

**Comment by alfespa17** [comment]
I did some changes in the logic to get the module versions, instead of reading the information in real time every time from the git service (github, gitlab, bitbucket, etc) when we are calling the module API we are now reading the information from REDIS cache.

This will improve the module performance a lot but the only tradeoff is that the cache version will be updated every 3 minutes.

**Comment by ruankr** [comment]
@alfespa17 I think that should hopefully not be an issue as we publish quite a lot of our own modules however typically they do not tend to change a lot. A new version is only created when an issue is found or a new provider/terraform version breaks it. Looking forward to test to see how it behaves once its ready! Thanks for the effort put in!

**Comment by alfespa17** [comment]
I created a beta release with the fix for this issue, if you want to try it in some test environment you could overwrite the API version in the helm chart like this:

```yaml
api:
  version: "2.16.0-beta.1"
```

I have been testing in minikube with over 40 modules and it works really fast loading that page.
