### ISSUE TITLE
Registry error introduced in 2.18.0

### ISSUE THREAD

**Issue by jderieg** [AzBuilder/terrakube#615]
### Bug description 🐞

Upgraded our Terrakube from 2.17.2 to 2.18.0. When running a plan against Terrakube now from our Github runners, we get the following when trying to connect to the registry in Terrakube:
![2023-12-01_10-58](https://github.com/AzBuilder/terrakube/assets/63372114/e0db22bc-ec98-4d4b-822d-44b66fb14f5e)

The registry pod shows the following error:
```
2023-12-01 17:35:45.563 ERROR 1 --- [nio-8075-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

io.jsonwebtoken.MalformedJwtException: The JWS header references signature algorithm 'RS256' but the compact JWE string is missing the required signature.
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:423) ~[jjwt-impl-0.12.3.jar:0.12.3]
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:362) ~[jjwt-impl-0.12.3.jar:0.12.3]
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:94) ~[jjwt-impl-0.12.3.jar:0.12.3]
	at io.jsonwebtoken.impl.io.AbstractParser.parse(AbstractParser.java:36) ~[jjwt-impl-0.12.3.jar:0.12.3]
	at io.jsonwebtoken.impl.io.AbstractParser.parse(AbstractParser.java:29) ~[jjwt-impl-0.12.3.jar:0.12.3]
	at io.jsonwebtoken.impl.DefaultJwtParser.parseUnsecuredClaims(DefaultJwtParser.java:807) ~[jjwt-impl-0.12.3.jar:0.12.3]
	at org.terrakube.registry.configuration.authentication.dex.RegistryAuthenticationManagerResolver.getJwtIssuer(RegistryAuthenticationManagerResolver.java:54) ~[classes/:2.18.0]
	at org.terrakube.registry.configuration.authentication.dex.RegistryAuthenticationManagerResolver.resolve(RegistryAuthenticationManagerResolver.java:36) ~[classes/:2.18.0]
	at org.terrakube.registry.configuration.authentication.dex.RegistryAuthenticationManagerResolver.resolve(RegistryAuthenticationManagerResolver.java:22) ~[classes/:2.18.0]
	at org.springframework.security.oauth2.server.resource.web.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:133) ~[spring-security-oauth2-resource-server-5.7.11.jar:5.7.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.30.jar:5.3.30]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.11.jar:5.7.11]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[spring-security-web-5.7.11.jar:5.7.11]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[spring-security-web-5.7.11.jar:5.7.11]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.11.jar:5.7.11]
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117) ~[spring-security-web-5.7.11.jar:5.7.11]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.30.jar:5.3.30]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.11.jar:5.7.11]
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-5.3.30.jar:5.3.30]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.30.jar:5.3.30]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.11.jar:5.7.11]
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-5.7.11.jar:5.7.11]
	...
```

I reverted to 2.17.2 and the Registry works as expected now.

### Steps to reproduce

Have the Registry set up with modules in Github. Upgrade to Terrakube 2.18.0 and try to use it. The registry pod throws errors.

### Expected behavior

Registry should continue working on upgrade.

**Comment by alfespa17** [comment]
I upgraded some libraries for this release, it looks that is the issue, I will check

**Comment by alfespa17** [comment]
For now you could rollback the registry version to 2.17.2

**Comment by jderieg** [comment]
Yup, I rolled back to 2.17.2 already and it works fine. I left my dev cluster on 2.18.0 in case you need me to check anything. Thanks!
BTW, we have completely migrated off of terraform.io onto our own Terrakube instance. My team loves it!

**Comment by alfespa17** [comment]
That sounds great, I am glad that your team is happy with Terrakube :+1:
