### ISSUE TITLE
Spring Redis health check fails when using default Redis setup

### ISSUE THREAD

**Issue by dcopestake** [AzBuilder/terrakube#749]
### Bug description 🐞

After trying to deploy the [2.20.0-beta.5](https://github.com/AzBuilder/terrakube/releases/tag/2.20.0-beta.5) release to test another fix, the API deployment pods are failing to become ready and throwing the following error:

```
Caused by: redis.clients.jedis.exceptions.JedisAccessControlException: WRONGPASS invalid username-password pair or user is disabled.
        at redis.clients.jedis.Protocol.processError(Protocol.java:136) ~[jedis-3.9.0.jar:na]
        at redis.clients.jedis.Protocol.process(Protocol.java:176) ~[jedis-3.9.0.jar:na]
        at redis.clients.jedis.Protocol.read(Protocol.java:230) ~[jedis-3.9.0.jar:na]
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:352) ~[jedis-3.9.0.jar:na]
        at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:270) ~[jedis-3.9.0.jar:na]
        at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2729) ~[jedis-3.9.0.jar:na]
        at redis.clients.jedis.BinaryJedis.initializeFromClientConfig(BinaryJedis.java:97) ~[jedis-3.9.0.jar:na]
        at redis.clients.jedis.BinaryJedis.<init>(BinaryJedis.java:297) ~[jedis-3.9.0.jar:na]
        at redis.clients.jedis.Jedis.<init>(Jedis.java:169) ~[jedis-3.9.0.jar:na]
        at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:177) ~[jedis-3.9.0.jar:na]
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[commons-pool2-2.11.1.jar:2.11.1]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[commons-pool2-2.11.1.jar:2.11.1]
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[commons-pool2-2.11.1.jar:2.11.1]
        at redis.clients.jedis.util.Pool.getResource(Pool.java:75) ~[jedis-3.9.0.jar:na]
        ... 132 common frames omitted

WARN 1 --- [nio-8080-exec-2] o.s.b.a.redis.RedisHealthIndicator       : Redis health check failed
```

This was _not_ happening with the previous build we had deployed, which was [2.20.0-beta.2](https://github.com/AzBuilder/terrakube/releases/tag/2.20.0-beta.2).

For reference we're using the API with `defaultRedis: true`.

### Steps to reproduce

1. Deploy [2.20.0-beta.5](https://github.com/AzBuilder/terrakube/releases/tag/2.20.0-beta.5) with the API configured with `defaultRedis: true`.
2. Tail the logs for the API during start-up, note that the Spring `RedisHealthIndicator` will fail

### Expected behavior

API initialises as expected and `RedisHealthIndicator` passes.

### Anything else?

I'm not 100%, but looking at the code I wonder if this is related to pull request #713 as it appears as if the Redis username is always being set now, but with the default configuration there is no value specified for the `TerrakubeRedisUsername` env var.

**Comment by alfespa17** [comment]
I will check that later today, I guess the problem is the username in #713, the strange thing is that it is working in gitpod when I was testing yesterday and I was using the same bitnami redis container.

**Comment by dcopestake** [comment]
@alfespa17 I only actually see the error fairly late on after the API starts up, basically once TomCat has actually started and bound to the listening port etc. Generally for me this takes about 4 minutes! At this point the exception is thrown. This makes sense as that's probably the first time the `/actuator` endpoint is being called by the pod probes.

Just looking at this a bit more, I think what might be happening here is that:

https://github.com/AzBuilder/terrakube/blob/cd5360fe361943104ef10772c650471177ae14c7/api/src/main/java/org/terrakube/api/plugin/streaming/StreamingProperties.java#L18

...is actually being set as an empty string rather than as `null` (see https://github.com/spring-projects/spring-boot/issues/24133), meaning that the result of:

https://github.com/AzBuilder/terrakube/blob/cd5360fe361943104ef10772c650471177ae14c7/api/src/main/java/org/terrakube/api/plugin/streaming/StreamingConfiguration.java#L58

...is that the username is actually being set to an empty string instead of `null`, which is throwing off the Redis `AUTH` command as it thinks it has a username to use specify along with the password. Obviously prior to PR #713 only the password was ever set, so this kind of makes sense.

If I'm correct then I guess just simply changing to:
```
String username = props.getUsername();
if (username != null && !username.isEmpty()) {
    redisStandaloneConfiguration.setUsername(props.getUsername());
}
```
...would fix this? 🤷‍♂️ 

Just FYI; I also noticed that the Executor's [RedisAutoConfiguration](https://github.com/AzBuilder/terrakube/blob/cd5360fe361943104ef10772c650471177ae14c7/executor/src/main/java/org/terrakube/executor/configuration/RedisAutoConfiguration.java) also seems to have the same issue and that the default properties for this:

https://github.com/AzBuilder/terrakube/blob/cd5360fe361943104ef10772c650471177ae14c7/executor/src/main/resources/application.properties#L104

...are currently set to `default` which was possibly missed when you applied https://github.com/AzBuilder/terrakube/commit/9fed97e20d693913a6dd23146647cacafd1908c7?

**Comment by alfespa17** [comment]
Thank you for your suggestion @dcopestake, now it is working after adding the validation as you suggested. I tested in minikube and it looks good to me, you could check [2.20.0-beta.6](https://github.com/AzBuilder/terrakube/releases/tag/2.20.0-beta.6) that version include #753 and #754 

Api example:
![image](https://github.com/AzBuilder/terrakube/assets/4461895/fe79390f-7dd7-47d9-ae2d-4d8f26f040c2)

Executor example:
![image](https://github.com/AzBuilder/terrakube/assets/4461895/e1d59997-4287-4f90-bcb4-516f55803d33)

**Comment by dcopestake** [comment]
All working, many thanks @alfespa17 🤝
