### ISSUE TITLE
SQL Azure Connection Issue in v2.20.0

### ISSUE THREAD

**Issue by alfespa17** [AzBuilder/terrakube#813]
### Bug description 🐞

When using SQL Azure with Terrakube 2.19.2 the connection is successfull

```
2024-04-15 19:10:25.285  INFO 1 --- [           main] org.terrakube.api.ServerApplication      : Starting ServerApplication v2.19.2 using Java 17.0.9 on terrakube-api-7d549f6d8d-fnfw4 with PID 1 (/workspace/BOOT-INF/classes started by cnb in /workspace)
2024-04-15 19:10:25.308  INFO 1 --- [           main] org.terrakube.api.ServerApplication      : The following 1 profile is active: "demo"
2024-04-15 19:10:30.379  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2024-04-15 19:10:30.382  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-04-15 19:10:31.679  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 1255 ms. Found 17 JPA repository interfaces.
2024-04-15 19:10:33.750  INFO 1 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=843dbc6e-ec02-3bb0-afdd-fd4040f2d001
2024-04-15 19:10:35.300  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2024-04-15 19:10:35.325  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-04-15 19:10:35.327  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.83]
2024-04-15 19:10:35.722  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-04-15 19:10:35.726  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 9651 ms
2024-04-15 19:10:35.937  INFO 1 --- [           main] o.t.a.p.d.DataSourceAutoConfiguration    : DataSourceType: SQL_AZURE
2024-04-15 19:10:38.787  INFO 1 --- [           main] liquibase.database                       : Set default schema name to dbo
2024-04-15 19:10:43.472  INFO 1 --- [           main] liquibase.lockservice                    : Successfully acquired change log lock
2024-04-15 19:10:45.029  INFO 1 --- [           main] liquibase.changelog                      : Creating database history table with name: DATABASECHANGELOG
2024-04-15 19:10:45.523  INFO 1 --- [           main] liquibase.changelog                      : Reading from DATABASECHANGELOG
2024-04-15 19:10:49.609  INFO 1 --- [           main] liquibase.servicelocator                 : Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
```

When using version 2.20.0 it is generating the following:

```
2024-04-15 19:18:32.760  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2239 ms
2024-04-15 19:18:32.860  INFO 1 --- [           main] o.t.a.p.d.DataSourceAutoConfiguration    : DataSourceType: SQL_AZURE
2024-04-15 19:18:33.319  INFO 1 --- [           main] o.t.a.p.s.StreamingConfiguration         : Redis Configuration=> User: username is null, Hostname: terrakube-redis-master, Port: 6379, Ssl: false
2024-04-15 19:18:33.320  INFO 1 --- [           main] o.t.a.p.s.StreamingConfiguration         : Redis connection is not using username parameter
2024-04-15 19:18:33.320  INFO 1 --- [           main] o.t.a.p.s.StreamingConfiguration         : Using default Redis connection
2024-04-15 19:18:34.850  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Cannot use default schema name public on Microsoft SQL Server because the login schema of the current user (dbo) is different and MSSQL does not support setting the default schema per session.
2024-04-15 19:18:34.859  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-04-15 19:18:34.875  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-04-15 19:18:34.890 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is java.lang.RuntimeException: Cannot use default schema name public on Microsoft SQL Server because the login schema of the current user (dbo) is different and MSSQL does not support setting the default schema per session.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.31.jar:5.3.31]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.31.jar:5.3.31]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar:5.3.31]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.31.jar:5.3.31]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.31.jar:5.3.31]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.31.jar:5.3.31]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.31.jar:5.3.31]

```

### Steps to reproduce

Deploy terrakube 2.20.0 using 

```
api:
  version: "2.20.0"
  defaultRedis: true
  defaultDatabase: false
  loadSampleData: true
  properties:
    databaseType: "SQL_AZURE"
    databaseHostname: "XXXX.database.windows.net"
    databaseName: "XXXX"
    databaseUser: "XXXX"
    databasePassword: "XXXX"
```

### Expected behavior

Connection to SQL Azure should work without any issue.

**Comment by alfespa17** [comment]
The workaround is to set the variable DatasourceSchema to "dbo"

```yaml
## API properties
api:
  version: "2.20.0"
  defaultRedis: true
  defaultDatabase: false
  loadSampleData: true
  env:
  - name: SERVICE_BINDING_ROOT
    value: /mnt/platform/bindings
  - name: DatasourceSchema
    value: "dbo"
  properties:
    databaseType: "SQL_AZURE"
    databaseHostname: "xxxxx.database.windows.net"
    databaseName: "xxxxx"
    databaseUser: "xxxxx"
    databasePassword: "xxxxx"
```

Using the above fixed it
```shell
2024-04-15 19:36:33.791  INFO 1 --- [           main] org.terrakube.api.ServerApplication      : Starting ServerApplication v2.20.0 using Java 17.0.10 on terrakube-api-5d9f54df78-n9tcq with PID 1 (/workspace/BOOT-INF/classes started by cnb in /workspace)
2024-04-15 19:36:33.793  INFO 1 --- [           main] org.terrakube.api.ServerApplication      : The following 1 profile is active: "demo"
2024-04-15 19:36:34.774  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2024-04-15 19:36:34.774  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-04-15 19:36:35.015  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 235 ms. Found 18 JPA repository interfaces.
2024-04-15 19:36:35.502  INFO 1 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=b37f76ff-0f9f-3f8b-8370-b5ba6ed89585
2024-04-15 19:36:35.997  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2024-04-15 19:36:36.004  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-04-15 19:36:36.005  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.83]
2024-04-15 19:36:36.131  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-04-15 19:36:36.131  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2225 ms
2024-04-15 19:36:36.258  INFO 1 --- [           main] o.t.a.p.d.DataSourceAutoConfiguration    : DataSourceType: SQL_AZURE
2024-04-15 19:36:36.539  INFO 1 --- [           main] o.t.a.p.s.StreamingConfiguration         : Redis Configuration=> User: username is null, Hostname: terrakube-redis-master, Port: 6379, Ssl: false
2024-04-15 19:36:36.540  INFO 1 --- [           main] o.t.a.p.s.StreamingConfiguration         : Redis connection is not using username parameter
2024-04-15 19:36:36.540  INFO 1 --- [           main] o.t.a.p.s.StreamingConfiguration         : Using default Redis connection
2024-04-15 19:36:42.023  INFO 1 --- [           main] liquibase.lockservice                    : Successfully acquired change log lock
2024-04-15 19:36:45.357  INFO 1 --- [           main] liquibase.changelog                      : Reading from DATABASECHANGELOG
2024-04-15 19:36:48.956  INFO 1 --- [           main] liquibase.servicelocator                 : Cannot load service: liquibase.hub.HubService: Provider liquibase.hub.core.StandardHubService could not be instantiated
2024-04-15 19:36:49.283  INFO 1 --- [           main] liquibase.lockservice                    : Successfully released change log lock
2024-04-15 19:36:50.025  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2024-04-15 19:36:50.058  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.15.Final
2024-04-15 19:36:50.175  INFO 1 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2024-04-15 19:36:51.143  INFO 1 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.SQLServer2012Dialect
2024-04-15 19:36:51.390  WARN 1 --- [           main] o.terrakube.api.rs.module.GitTagsCache   : Module Config: MaxTotal 128 MaxIdle 128 MinIdle 64 Timeout 600000 Schedule 0 */3 * ? * *
2024-04-15 19:36:51.390  WARN 1 --- [           main] o.terrakube.api.rs.module.GitTagsCache   : Connecting Default Redis using hostname, port and password
2024-04-15 19:36:51.391  INFO 1 --- [           main] o.terrakube.api.rs.module.GitTagsCache   : Redis connection completed...

```

The issue is related to this particular default value:

https://github.com/AzBuilder/terrakube/blob/3f9589f775e755d7cb739410f57514e3bd479646/api/src/main/resources/application.properties#L39

**Comment by iam-take** [comment]
I had this same issue yesterday, I will reconfigure today to see if the workaround fixes it for me as well :)

**Comment by iam-take** [comment]
I can confirm that for me this workaround is working as well. Thanks for the info as this helps us use or prefered DB type 😄

**Comment by alfespa17** [comment]
Documentation has been updated here for sql azure database

https://docs.terrakube.io/getting-started/deployment/database-backend/sql-azure

The helm chart version 3.16.2 now has an option to set the schema like this:

```
## API properties
api:
  properties:
    databaseType: "SQL_AZURE"
    databaseHostname: "xxxxx.database.windows.net"
    databaseName: "xxxxx"
    databaseUser: "xxxxx"
    databasePassword: "xxxxx"
    databaseSchema: "dbo"
```
