### ISSUE TITLE
API error on fresh install

### ISSUE THREAD

**Issue by tszebeni** [AzBuilder/terrakube#846]
### Bug description 🐞

Dear maintainers, I'm testing terrakube via docker compose and with/without traefik config. My problem is with traefik integration, as I receive the following error in browser:
I configured tk.net as my test domain. Xhr request has been sent to "https://tk-api.tk.net/api/v1/organization" after I logged into the UI app. The problem is that it responds as:
Error 502 
```
{
    "timestamp": "2024-05-13T15:27:42.708+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/api/v1/organization"
}
```
When I look at docker-compose logs, I see:
```
terrakube-api           | 2024-05-13 15:24:43.286 ERROR 1 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception   
terrakube-api           | 
terrakube-api           | java.lang.IllegalArgumentException: Unable to resolve the Configuration with the provided Issuer of "https://tk-dex.tk.net/dex"
terrakube-api           |       at org.springframework.security.oauth2.jwt.JwtDecoderProviderConfigurationUtils.getConfiguration(JwtDecoderProviderConfigurationUtils.java:161) ~[spring-security-oauth2-jose-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.oauth2.jwt.JwtDecoderProviderConfigurationUtils.getConfigurationForIssuerLocation(JwtDecoderProviderConfigurationUtils.java:79) ~[spring-security-oauth2-jose-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.oauth2.jwt.JwtDecoders.fromIssuerLocation(JwtDecoders.java:93) ~[spring-security-oauth2-jose-5.7.11.jar:5.7.11]
terrakube-api           |       at org.terrakube.api.plugin.security.authentication.dex.DexAuthenticationManagerResolver.resolve(DexAuthenticationManagerResolver.java:69) ~[classes/:2.20.0]
terrakube-api           |       at org.terrakube.api.plugin.security.authentication.dex.DexAuthenticationManagerResolver.resolve(DexAuthenticationManagerResolver.java:31) ~[classes/:2.20.0]
terrakube-api           |       at org.springframework.security.oauth2.server.resource.web.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:133) ~[spring-security-oauth2-resource-server-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186) ~[spring-security-web-5.7.11.jar:5.7.11]
terrakube-api           |       at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.7.18.jar:2.7.18]
terrakube-api           |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.83.jar:9.0.83]
terrakube-api           |       at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
terrakube-api           | Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://tk-dex.tk.net/dex/.well-known/openid-configuration": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
terrakube-api           |       at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:791) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:676) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.security.oauth2.jwt.JwtDecoderProviderConfigurationUtils.getConfiguration(JwtDecoderProviderConfigurationUtils.java:150) ~[spring-security-oauth2-jose-5.7.11.jar:5.7.11]
terrakube-api           |       ... 67 common frames omitted
terrakube-api           | Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
terrakube-api           |       at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source) ~[na:na]
terrakube-api           |       at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:782) ~[spring-web-5.3.31.jar:5.3.31]
terrakube-api           |       ... 69 common frames omitted
terrakube-api           | Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
terrakube-api           |       at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.validator.Validator.validate(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source) ~[na:na]
terrakube-api           |       ... 88 common frames omitted
terrakube-api           | Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
terrakube-api           |       at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source) ~[na:na]
terrakube-api           |       at java.base/java.security.cert.CertPathBuilder.build(Unknown Source) ~[na:na]
terrakube-api           |       ... 93 common frames omitted
```
The URL https://tk-dex.tk.net/dex/.well-known/openid-configuration serves its content well.
Also Login works on url https://tk-dex.tk.net/dex/auth/ldap/login

Please advise 

### Steps to reproduce

1. Follow docker compose + traefik documentation
2. Login to UI app
3. open inspector in browser to see network error

### Expected behavior

All the example configuration should load into the application

**Comment by alfespa17** [comment]
I guess you are using some self signed certificates you will have to add the CA certificate to the API, Registry and Executor container this reference can help you:

https://gist.github.com/SolomonHD/b55be40146b7a53b8f26fe244f5be52e?permalink_comment_id=5004300#gistcomment-5004300

https://gist.github.com/SolomonHD/b55be40146b7a53b8f26fe244f5be52e?permalink_comment_id=5004324#gistcomment-5004324

**Comment by tszebeni** [comment]
Thanks @alfespa17!
 I could fix it accordingly my docker compose setup with Traefik.
My aim is to use terrakube in a kubernetes cluster on GCP, but I cannot get the ingress configuration right.
My problem there is that the same api request is routed to ui service and produces such an error message, do you have a hint there too?
I'm also interested of the setup needed for production workload, but I have very limited k8s knowledge unfortunately.

**Comment by alfespa17** [comment]
Can you share your helm chart ingress config values @tszebeni? (without any sensitive data)
