### ISSUE TITLE
Redis Connection not working

### ISSUE THREAD

**Issue by iam-take** [AzBuilder/terrakube#849]
### Bug description 🐞

We have Terrakube running for a while now. But since a few days when we try to deploy a new cluster for a more production environment we are receiving Redis errors in the API Pod. I can't find out what is the issue with this. The configuration remains the same as before and the other cluster showed us the same error today. 

Using a external Redis solution makes a workaround for now but it would be much appriacted if anybody could help us out with this issue. 

**Error log from the API Pod**
```text

2024-05-15 13:16:54.294 WARN 1 --- [nio-8080-exec-1] o.s.b.a.redis.RedisHealthIndicator : Redis health check failed
org.springframework.data.redis.RedisConnectionFailureException: Cannot get Jedis connection nested exception is redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.fetchJedisConnector(JedisConnectionFactory.java:292) ~[spring-data-redis-2.7.18.jar:2.7.18]
at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.getConnection(JedisConnectionFactory.java:515) ~[spring-data-redis-2.7.18.jar:2.7.18]
at org.springframework.data.redis.core.RedisConnectionUtils.fetchConnection(RedisConnectionUtils.java:193) ~[spring-data-redis-2.7.18.jar:2.7.18]
at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:144) ~[spring-data-redis-2.7.18.jar:2.7.18]
at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:105) ~[spring-data-redis-2.7.18.jar:2.7.18]
at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:92) ~[spring-data-redis-2.7.18.jar:2.7.18]
at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82) ~[spring-boot-actuator-2.7.18.jar:2.7.18]
at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37) ~[spring-boot-actuator-2.7.18.jar:2.7.18]
at org.springframework.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:104) ~[spring-boot-actuator-2.7.18.jar:2.7.18]
at org.springframework.boot.actuate.health.HealthEndpointWebExtension.getHealth(HealthEndpointWebExtension.java:46) ~[spring-boot-actuator-2.7.18.jar:2.7.18]
at org.springframework.boot.actuate.health.HealthEndpointSupport.getLoggedHealth(HealthEndpointSupport.java:172) ~[spring-boot-actuator-2.7.18.jar:2.7.18]
at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:145) ~[spring-boot-actuator-2.7.18.jar:2.7.18]
at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateContribution(HealthEndpointSupport.java:156) ~[spring-boot-actuator-2.7.18.jar:2.7.18]
at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:141) ~[spring-boot-actuator-2.7.18.jar:2.7.18]
at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:110) ~[spring-boot-actuator-2.7.18.jar:2.7.18]
at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:81) ~[spring-boot-actuator-2.7.18.jar:2.7.18]

```

### Steps to reproduce

Unsure

**Comment by alfespa17** [comment]
You can also customize some redis paramaters related to the connection with the helm chart with this:

https://github.com/AzBuilder/terrakube-helm-chart/blob/ad9490ee6cd1f32ed1888acc807a87f5d66c60f4/charts/terrakube/values.yaml#L179

**Comment by iam-take** [comment]
Thanks for the quick response @alfespa17. 

I've done some more digging in the AKS Cluster and it seems that Azure Policy has been enabled since a few days. Since a upgrade was done of my cluster today the pods needed to be restarted as well. And now Azure Policy is blocking the pod from being started as the Redis pod seems to require Privilege escalation which Azure Policy isn't a fan of. 

I've disabled Azure Policy on the AKS Cluster and I can confirm that it is now working again.
