### ISSUE TITLE
ConnectTimeoutException When proxy is used

### ISSUE THREAD

**Issue by tszebeni-asml** [AzBuilder/terrakube#902]
### Bug description 🐞

When a proxy is being used, via JAVA_TOOL_OPTIONS environment variables in a docker-compose environment, I noticed that when VCS integration is made, the following error occurs. It cannot connect terrakube to github:

```
terrakube-api         | 2024-05-31 06:51:14.979  INFO 1 --- [io-8080-exec-10] o.t.a.p.v.controller.CallbackController  : Updating connection for vcs cb46a180-1f16-11ef-b70e-953d9b79f8aa
terrakube-api         | 2024-05-31 06:51:15.034  INFO 1 --- [io-8080-exec-10] o.terrakube.api.plugin.vcs.TokenService  : VCS found with custom callback
terrakube-api         | 2024-05-31 06:51:46.127 ERROR 1 --- [io-8080-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.reactive.function.client.WebClientRequestException: connection timed out: github.com/140.82.121.3:443; nested exception is io.netty.channel.ConnectTimeoutException: connection timed out: github.com/140.82.121.3:443] with root cause
terrakube-api         | 
terrakube-api         | io.netty.channel.ConnectTimeoutException: connection timed out: github.com/x.x.x.x:443
terrakube-api         |         at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:613) ~[netty-transport-classes-epoll-4.1.101.Final.jar:4.1.101.Final]
terrakube-api         |         at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
terrakube-api         |         at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
terrakube-api         |         at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
terrakube-api         |         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
terrakube-api         |         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
terrakube-api         |         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[netty-transport-classes-epoll-4.1.101.Final.jar:4.1.101.Final]
terrakube-api         |         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
terrakube-api         |         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
terrakube-api         |         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.101.Final.jar:4.1.101.Final]
terrakube-api         |         at java.base/java.lang.Thread.run(Unknown Source) ~[na:na
```

### Steps to reproduce

Deploy application without internet access and configure proxy.
Other functionalities seems working, as respects the configuration to use proxy.
From the vm the code is deployed I verified that github.com is reachable through the proxy.

### Expected behavior

NIO requests should also use the proxy service.

**Comment by alfespa17** [comment]
Hello @tszebeni-asml 

Can you share an example of the JAVA_TOOL_OPTIONS  that you are using?

Did you add it like the following:

```
JAVA_TOOL_OPTIONS="-Dhttp.proxyHost=your.proxy.net -Dhttp.proxyPort=8080 -Dhttp.nonProxyHosts=XXXXX -Dhttps.proxyHost=your.proxy.net -Dhttps.proxyPort=8080 -Dhttps.nonProxyHosts=XXXXX"
```

**Comment by alfespa17** [comment]
Not sure if your issue is related to this https://github.com/reactor/reactor-netty/issues/887#issuecomment-549439355

In this part of the code:

https://github.com/AzBuilder/terrakube/blob/bf227f5cc07505a5184761646d8c94c8e15cd800/api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubTokenService.java#L16

**Comment by tszebeni-asml** [comment]
Hi @alfespa17 , I believe that is related. I'm using the proxy config as in your example, and proxy works for other requests I could see in the application.

**Comment by alfespa17** [comment]
Hello @tszebeni-asml I created a small fix but not sure if that will work because I dont have a proxy to test. You can use the following version to validate if my fix solved your issues.

https://github.com/AzBuilder/terrakube/releases/tag/2.21.1-proxy-fix

If that works for you I will merge the change to the main branch

**Comment by gfranco-nos** [comment]
@alfespa17 I was with the same problem and the fix in the 2.21.1-proxy-fix fixed for me. Is is applied in the latest version?

**Comment by alfespa17** [comment]
> @alfespa17 I was with the same problem and the fix in the 2.21.1-proxy-fix fixed for me. Is is applied in the latest version?

I never merged the PR, because I never got any confirmation and I didn't have a way to test it

**Comment by alfespa17** [comment]
> > @alfespa17 I was with the same problem and the fix in the 2.21.1-proxy-fix fixed for me. Is is applied in the latest version?
> 
> I never merged the PR, because I never got any confirmation and I didn't have a way to test it

@gfranco-nos

**Comment by alfespa17** [comment]
> I imagined this looking the release notes, but works great!
> 
> ![image](https://private-user-images.githubusercontent.com/156679086/375547546-7533fe9b-805a-43c0-8e5a-5449117eddfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1OTUzNDEsIm5iZiI6MTcyODU5NTA0MSwicGF0aCI6Ii8xNTY2NzkwODYvMzc1NTQ3NTQ2LTc1MzNmZTliLTgwNWEtNDNjMC04ZTVhLTU0NDkxMTdlZGRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQyMTE3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWM5MTQwNzkxYjM3ZjQ4ZTk0YTcxYjAzYzlkNjBiMzdmNGM0NmQyNWM4MTc3ZDc2ZmViOGExMmE1YWY5MWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FDVOYPIu45uYmXAfQyISZIy184NFLgbTHLt_viQI5lI)

In that case I will fix the merge issue and merge that change to main branch, maybe tomorrow

**Comment by gfranco-nos** [comment]
Bad news.. Not working in the workspace routines:

```
2024-10-10T21:27:06.802Z ERROR 1 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.terrakube.api.rs.Organization.template: could not initialize proxy - no Session] with root cause

org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.terrakube.api.rs.Organization.template: could not initialize proxy - no Session
	at org.hibernate.collection.spi.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:635) ~[hibernate-core-6.2.22.Final.jar:6.2.22.Final]
	at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:218) ~[hibernate-core-6.2.22.Final.jar:6.2.22.Final]
	at org.hibernate.collection.spi.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:615) ~[hibernate-core-6.2.22.Final.jar:6.2.22.Final]
	at org.hibernate.collection.spi.AbstractPersistentCollection.read(AbstractPersistentCollection.java:136) ~[hibernate-core-6.2.22.Final.jar:6.2.22.Final]
	at org.hibernate.collection.spi.PersistentBag.iterator(PersistentBag.java:371) ~[hibernate-core-6.2.22.Final.jar:6.2.22.Final]
	at org.terrakube.api.plugin.vcs.WebhookService.createWorkspaceWebhook(WebhookService.java:159) ~[classes/:2.21.1-proxy-fix]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-6.0.18.jar:6.0.18]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[spring-aop-6.0.18.jar:6.0.18]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-6.0.18.jar:6.0.18]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) ~[spring-aop-6.0.18.jar:6.0.18]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-6.0.18.jar:6.0.18]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391) ~[spring-tx-6.0.18.jar:6.0.18]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-6.0.18.jar:6.0.18]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.18.jar:6.0.18]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) ~[spring-aop-6.0.18.jar:6.0.18]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) ~[spring-aop-6.0.18.jar:6.0.18]
	at org.terrakube.api.plugin.vcs.WebhookService$$SpringCGLIB$$0.createWorkspaceWebhook(<generated>) ~[classes/:2.21.1-proxy-fix]
	at org.terrakube.api.rs.hooks.workspace.WorkspaceManageHook.execute(WorkspaceManageHook.java:58) ~[classes/:2.21.1-proxy-fix]
	at org.terrakube.api.rs.hooks.workspace.WorkspaceManageHook.execute(WorkspaceManageHook.java:18) ~[classes/:2.21.1-proxy-fix]
	at com.yahoo.elide.core.lifecycle.LifeCycleHook.execute(LifeCycleHook.java:45) ~[elide-core-7.0.5.jar:na]
	at com.yahoo.elide.core.lifecycle.LifecycleHookInvoker.lambda$onNext$0(LifecycleHookInvoker.java:43) ~[elide-core-7.0.5.jar:na]
	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
	at com.yahoo.elide.core.lifecycle.LifecycleHookInvoker.onNext(LifecycleHookInvoker.java:42) ~[elide-core-7.0.5.jar:na]
	at com.yahoo.elide.core.RequestScope.lambda$notifySubscribers$4(RequestScope.java:258) ~[elide-core-7.0.5.jar:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[na:na]
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at com.yahoo.elide.core.RequestScope.notifySubscribers(RequestScope.java:257) ~[elide-core-7.0.5.jar:na]
	at com.yahoo.elide.core.RequestScope.runQueuedPostCommitTriggers(RequestScope.java:300) ~[elide-core-7.0.5.jar:na]
	at com.yahoo.elide.jsonapi.JsonApi.handleRequest(JsonApi.java:294) ~[elide-core-7.0.5.jar:na]
	at com.yahoo.elide.jsonapi.JsonApi.post(JsonApi.java:129) ~[elide-core-7.0.5.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:281) ~[spring-core-6.0.18.jar:6.0.18]
	at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:482) ~[spring-cloud-context-4.1.2.jar:4.1.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.18.jar:6.0.18]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:751) ~[spring-aop-6.0.18.jar:6.0.18]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:703) ~[spring-aop-6.0.18.jar:6.0.18]
	at com.yahoo.elide.jsonapi.JsonApi$$SpringCGLIB$$0.post(<generated>) ~[elide-core-7.0.5.jar:na]
	at com.yahoo.elide.spring.controllers.JsonApiController$2.call(JsonApiController.java:112) ~[elide-spring-boot-autoconfigure-7.0.5.jar:na]
	at com.yahoo.elide.spring.controllers.JsonApiController$2.call(JsonApiController.java:102) ~[elide-spring-boot-autoconfigure-7.0.5.jar:na]
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startCallableProcessing$4(WebAsyncManager.java:354) ~[spring-web-6.0.18.jar:6.0.18]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by alfespa17** [comment]
That is a different error try using the latest stable version please.

**Comment by gfranco-nos** [comment]
Ok, let me set up a local instance here and skip this proxy steps to know if I'm doing everything as I should..

**Comment by gfranco-nos** [comment]
Ok! It's working the issue was related with the no_proxy variable without the ```terrakube-*``` hosts :)

**Comment by alfespa17** [comment]
Use the latest image please 2.23.2, I will merge https://github.com/AzBuilder/terrakube/pull/931 once I fix the conflicts, I guess the proxy image has another bugs that we fixed in later versions.

**Comment by alfespa17** [comment]
I merged the changes, this feature can be tested using the following version.

2.24.0-beta.1

Feel free to leave any comment or suggestion testing that version
